---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fullname" . }}
spec:
  restartPolicy: Never
  containers:
  - name: zero-ci
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: Always
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    env:
    - name: REPO
      value: "{{ .Values.repo }}"
    - name: DOCKER_KEY
      valueFrom:
        secretKeyRef:
          name: docker-registry
          key: key
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
