apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-hook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{template "fullname" .}}
    spec:
      containers:
      - name: web-hook
        image:  nginx
        ports:
        - containerPort: 443
