apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-hook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-hook
    spec:
      containers:
      - name: web-hook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
