apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-hook
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - "ci.health-samurai.io"
    secretName: tls
  rules:
  - host: "ci.health-samurai.io"
    http:
      paths:
      - path: /*
        backend:
          serviceName: web-hook
          servicePort: 80
