apiVersion: v1
kind: Service
metadata:
  name: web-hook
  labels:
    app: web-hook
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: web-hook
