---
apiVersion: v1
kind: Pod
metadata:
  name: zero-ci
spec:
  restartPolicy: Never
  containers:
  - name: zero-ci
    image: eu.gcr.io/aidbox-next/zero-ci-runner:0.0.1
    imagePullPolicy: Always
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    env:
    - name: REPO
      value: https://github.com/niquola/zero-ci.git
    - name: DOCKER_KEY
      valueFrom:
        secretKeyRef:
          name: docker-registry
          key: key
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
